name = "move-car-api"
main = "src/index.js"
compatibility_date = "2026-06-09"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "move-car-db"
database_id = "474f1d5a-e4bc-4081-8eb6-47a8be2fa577"
migrations_dir = "migrations"
